// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SendRaw(arg1) {
  return window['go']['main']['App']['SendRaw'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetFanMode(arg1) {
  return window['go']['main']['App']['SetFanMode'](arg1);
}

export function SetFanSwitch(arg1) {
  return window['go']['main']['App']['SetFanSwitch'](arg1);
}
