// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect():Promise<boolean>;

export function Disconnect():Promise<void>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<main.Status>;

export function SendRaw(arg1:string):Promise<string>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetFanMode(arg1:number):Promise<boolean>;

export function SetFanSwitch(arg1:boolean):Promise<boolean>;
